import { describe, expect, it } from "vitest";
import { createMockAiCommandProvider, validateDrawingCommands } from "../src/ai";

describe("validateDrawingCommands", () => {
  it("accepts commands generated by the mock provider", async () => {
    const provider = createMockAiCommandProvider();
    const result = await provider.parseCommand("生成一个用户登录流程图", {
      objects: [],
    });

    expect(result.ok).toBe(true);

    if (!result.ok) {
      throw new Error(result.reason);
    }

    const validation = validateDrawingCommands(result.commands);

    expect(validation).toMatchObject({
      ok: true,
    });

    if (!validation.ok) {
      throw new Error(validation.errors[0].message);
    }

    expect(validation.commands).toHaveLength(5);
    expect(validation.commands[0]).toMatchObject({
      type: "create",
      shape: "text",
      text: "输入账号",
    });
  });

  it("strips unknown fields from accepted commands", () => {
    const validation = validateDrawingCommands([
      {
        type: "create",
        shape: "circle",
        style: {
          fill: "#ef4444",
        },
        dangerousUrl: "https://example.com/should-not-survive",
      },
    ]);

    expect(validation.ok).toBe(true);

    if (!validation.ok) {
      throw new Error(validation.errors[0].message);
    }

    expect("dangerousUrl" in validation.commands[0]).toBe(false);
  });

  it("rejects payloads that are not command arrays", () => {
    const validation = validateDrawingCommands({
      type: "create",
      shape: "circle",
    });

    expect(validation).toMatchObject({
      ok: false,
      errors: [
        {
          path: "",
          message: "AI 输出必须是命令数组。",
        },
      ],
    });
  });

  it("rejects unsupported command types", () => {
    const validation = validateDrawingCommands([
      {
        type: "eval",
        script: "alert(1)",
      },
    ]);

    expect(validation).toMatchObject({
      ok: false,
      errors: [
        {
          path: "[0].type",
          message: "不支持的命令类型“eval”。",
        },
      ],
    });
  });

  it("rejects invalid nested command fields", () => {
    const validation = validateDrawingCommands([
      {
        type: "update",
        target: {
          ref: "active",
        },
        patch: {
          fill: "red",
        },
      },
      {
        type: "move",
        target: {
          ref: "query",
          query: {},
        },
        direction: "diagonal",
      },
    ]);

    expect(validation).toMatchObject({
      ok: false,
      errors: [
        {
          path: "[0].patch.fill",
          message: "颜色必须是十六进制颜色值。",
        },
        {
          path: "[1].target.query",
          message: "目标查询至少需要一个条件。",
        },
      ],
    });
  });

  it("rejects overly long command plans", () => {
    const validation = validateDrawingCommands(
      Array.from({ length: 21 }, () => ({
        type: "create",
        shape: "circle",
      })),
    );

    expect(validation).toMatchObject({
      ok: false,
      errors: [
        {
          path: "",
          message: "AI 输出命令数量不能超过 20 条。",
        },
      ],
    });
  });
});
